root: true
parser: "@typescript-eslint/parser"
parserOptions:
   ecmaVersion: 11
   sourceType: module
   ecmaFeatures:
      jsx: true
env:
  node: true
  es6: true
  browser: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
plugins:
   - "@typescript-eslint"
   - react-hooks
rules:
   react/react-in-jsx-scope: off
   react-hooks/rules-of-hooks: error
   react-hooks/exhaustive-deps: warn
   "@typescript-eslint/explicit-function-return-type": off
