import { Inter } from 'next/font/google';
import Header from '@components/commons/Header';
import './global.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable}`}>
      <Header />
      <body>{children}</body>
    </html>
  );
}
